version: "3"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: weeve-egress-mqtt
      EGRESS_URL: https://hookb.in/example
      INGRESS_PORT: 80
      MQTT_BROKER: mqtt://test.mosquitto.org
      PORT: 1883
      TOPIC: weeve/factory
      QOS: 0
      LABELS:
    ports:
      - 5000:80
