version: "3.0"
services:
    mqtt-egress:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            MODULE_NAME: mqtt-egress
            MODULE_TYPE: Output
            INGRESS_HOST: "0.0.0.0"
            INGRESS_PORT: 80
            MQTT_BROKER: test.mosquitto.org
            PORT: 1883
            TOPIC: weeve/factory
            QOS: 0
            LABELS:
            LOG_LEVEL: DEBUG
        ports:
            - 8080:80
